basic:
    name: 'https://www.beatbread.com'
    environments:
        production: 'https://www.beatbread.com'
        staging: 'https://development.beatbread.com/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 768
        - 1200
    pages:
        - /
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 0
    scroll: true
    headers:
        - { value: 'en-US,en;q=0.9', header: accept-language }
        - { value: '1', header: upgrade-insecure-requests }
        - { value: '?1', header: sec-fetch-user }
        - { value: none, header: sec-fetch-site }
        - { value: navigate, header: sec-fetch-mode }
        - { value: document, header: sec-fetch-dest }
        - { header: Accept, value: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' }
        - { header: Connection, value: keep-alive }
        - { header: Upgrade-Insecure-Requests, value: '1' }
    cookies: ''
    custom_js: ''
    custom_css: "html, body, #root {\n   position: unset !important;\n\toverflow: auto !important;\n    display: block !important;\n    opacity: 1 !important;\n}"
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: '13'
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: false
